environment:
  NODE_ENV: test
  matrix:
    - nodejs_version: 8
    - nodejs_version: 10
platform:
  - x86
  - x64
install:
  - ps: Install-Product node $env:nodejs_version
  - npm config set progress=false
  - npm install
test_script: npm run test
build: off
cache: node_modules
