trigger:
  - master

jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-16.04
    strategy:
      maxParallel: 5
      matrix:
        node-12:
          node_version: ^12.0.0
          webpack_version: latest
        node-10:
          node_version: ^10.13.0
          webpack_version: latest
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)
        displayName: 'Install Node.js $(node_version)'
      - task: Npm@1
        inputs:
          command: custom
          customCommand: i -g npm@latest
        displayName: 'Install latest NPM'
      - script: |
          node -v
          npm -v
        displayName: 'Print versions'
      - task: Npm@1
        inputs:
          command: custom
          customCommand: ci
        displayName: 'Install dependencies'
      - script: npm run setup
        displayName: 'Setup monorepo'
      - script: npm i codecov
        displayName: 'Install codecov'
      - script: npm run test:ci
        displayName: 'Run tests with coverage'
      - script: cd samples/intro && npm i && npm run build
        displayName: 'Build'

  - job: macOS
    pool:
      vmImage: macOS-10.14
    strategy:
      maxParallel: 5
      matrix:
        node-12:
          node_version: ^12.0.0
          webpack_version: latest
        node-10:
          node_version: ^10.13.0
          webpack_version: latest
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)
        displayName: 'Install Node.js $(node_version)'
      - task: Npm@1
        inputs:
          command: custom
          customCommand: i -g npm@latest
        displayName: 'Install latest NPM'
      - script: |
          node -v
          npm -v
        displayName: 'Print versions'
      - task: Npm@1
        inputs:
          command: custom
          customCommand: ci
        displayName: 'Install dependencies'
      - script: npm run setup
        displayName: 'Setup monorepo'
      - script: npm i codecov
        displayName: 'Install codecov'
      - script: npm run test:ci
        displayName: 'Run tests with coverage'
      - script: cd samples/intro && npm i && npm run build
        displayName: 'Build'

  - job: Windows
    pool:
      vmImage: windows-2019
    strategy:
      maxParallel: 5
      matrix:
        # npm run bootstrap cannot be run
        # node-12:
        #   node_version: ^12.0.0
        #   webpack_version: latest
        node-10:
          node_version: ^10.13.0
          webpack_version: latest
    steps:
      - script: 'git config --global core.autocrlf input'
        displayName: 'Config git core.autocrlf'
      - checkout: self
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)
        displayName: 'Install Node.js $(node_version)'
      - task: Npm@1
        inputs:
          command: custom
          customCommand: i -g npm@latest
        displayName: 'Install latest NPM'
      - script: |
          node -v
          npm -v
        displayName: 'Print versions'
      - task: Npm@1
        inputs:
          command: custom
          customCommand: ci
        displayName: 'Install dependencies'
      - script: npm run setup
        displayName: 'Setup monorepo'
      - script: npm i codecov
        displayName: 'Install codecov'
      - script: npm run test:ci
        displayName: 'Run tests with coverage'
      # - script: cd samples/intro && npm i && npm run build
      #   displayName: 'Build'
