meta:
  title: What's Fusuma?
  description: Introduce Fusuma
  siteName: hiroppy.me
  sns: ['twitter']
slide:
  showIndex: true
  code:
    languages:
      - yaml
      - json
      - markdown
      - javascript
      - css
extends:
  js: index.js
  css: style.css
