meta:
  url: https://hiroppy.github.io/fusuma/intro/
  title: What's Fusuma?
  description: Introduce Fusuma
  siteName: hiroppy.me
  sns: ['twitter']
slide:
  ui:
    pagination:
extends:
  js: index.js
build:
  useCache: false
