import { Box, Heading, Text } from '@chakra-ui/react';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { tomorrow } from 'react-syntax-highlighter/dist/cjs/styles/prism';
import { DocsLayout } from '../../components/DocsLayout';
import { Link } from '../../components/Link';
import { slides } from '../../../../samples/intro/slides/04-slide.md';

const Section = ({ title, content, description, url }) => (
  <Box display={{ md: 'flex' }} gridGap={4} mt={10}>
    <Box textAlign="left" width={{ md: '50%' }}>
      <Heading size="md" mb={4}>
        {title}
      </Heading>
      <Text>{description}</Text>
      {content.map(({ code, lang }, i) => (
        <SyntaxHighlighter language={lang} style={tomorrow} key={i}>
          {code}
        </SyntaxHighlighter>
      ))}
    </Box>
    <Box width={{ md: '50%' }}>
      <iframe
        src={url}
        width="100%"
        height="100%"
        style={{ minHeight: 320, border: '1px solid #ccc' }}
      />
    </Box>
  </Box>
);

const Syntax = () => (
  <DocsLayout
    title="Slide Syntax"
    paths={[
      {
        name: 'slide syntax',
        path: '/slide-syntax',
      },
    ]}
  >
    <Box mt={6}>
      <Text>
        Fusuma provides several syntaxes using HTML comments to reduce code-writing mainly CSS and
        HTML. <br /> This page is generated by{' '}
        <Link href="https://github.com/hiroppy/fusuma/blob/master/samples/intro/slides/04-slide.md">
          intro#04
        </Link>
        .
      </Text>
    </Box>
    {slides.map((props) => (
      <Section {...props} key={props.title} />
    ))}
  </DocsLayout>
);

export default Syntax;
