meta:
  url: https://hiroppy.github.io/fusuma/debug
  title: debug
  description: A place which produces to resolve issues
  siteName: hiroppy.me
  sns: ['twitter']
slide:
  targetBlank: true
  ui:
    sidebar: true
    pagination: bullets
extends:
  js: main.js
build:
  useCache: false
